Add: container-build-push as action
greenbone/workflows pull request #17
Opened 2023-07-04 01:08 UTC by pascalholthaus

## What
Add: container-build-push as action

## Why
We need as an action to bypass secrets as build args

## References
None

2023-07-04 05:46 UTC, bjoernricks requested changes
Some things that should be addressed:
* The actions should go into our actions repo.
* All input descriptions should reflect the defaults
* Documentation in the README is missing

2023-07-04 05:46 UTC, bjoernricks commented on .github/actions/container-build-push-3rd-gen/action.yaml
> +    description: "Path to the docker file."
```suggestion
    description: "Path to the docker file. Default is './Dockerfile'."
```

2023-07-04 05:46 UTC, bjoernricks commented on .github/actions/container-build-push-3rd-gen/action.yaml
> +    description: "Path to image build context."
```suggestion
    description: "Path to image build context. Default is the current directory."
```

2023-07-04 05:46 UTC, bjoernricks commented on .github/actions/container-build-push-3rd-gen/action.yaml
> +    description: "Image platforms to build for."
```suggestion
    description: "Image platforms to build for. Default is 'linux/amd64'."
```

2023-07-04 05:46 UTC, bjoernricks commented on .github/actions/container-build-push-3rd-gen/action.yaml
> +    description: "Registry domain."
```suggestion
    description: "Registry domain. Default is 'ghcr.io'."
```

2023-07-04 06:25 UTC, pascalholthaus commented
Sure do you want all actions in our actions repo? Not only the generic action?

2023-07-10 06:57 UTC, y0urself reviewed
Why not add checkout to the action itself: https://github.com/greenbone/actions/blob/main/container-build-push-generic/action.yaml#L64 ?

2023-07-10 08:11 UTC, pascalholthaus commented
Because sometimes we maybe use the action in an other workflow. Like this https://github.com/greenbone/scan-management-frontend/pull/748 and a double checkout causes the git folder to be recreated.

2023-07-10 08:15 UTC, y0urself commented
> Because sometimes we maybe use the action in an other workflow. Like this https://github.com/greenbone/scan-management-frontend/pull/748 and a double checkout causes the git folder to be recreated.


We can remove it there, too?
Our approach in other actions is, always run the checkout in the action... AFAIK ... so this doesn't feel right for me ...
IMO this should be done in the action .. what do you think @bjoernricks ?

2023-07-10 08:25 UTC, y0urself approved these changes

2023-07-10 09:02 UTC, bjoernricks approved these changes

2023-07-10 09:02 UTC, merged

2023-07-10 09:18 UTC, bjoernricks commented
Sorry for not noticing the discussion. It depends. Afaik also running the checkout twice should work because it checks if there is already a checkout. But nevertheless when using the action we should at least allow to forwards the ref for the checkout and the depth if these aren't specific to the action.